script: |
  cd /home/ec2-user

  rm -rf devops-nginx-project

  git clone https://github.com/nikhilgeography-png/devops-nginx-project.git

  cd devops-nginx-project

  docker build -t nginx-project .

  docker stop nginx-project || true
  docker rm nginx-project || true

  docker run -d -p 80:80 --name nginx-project nginx-project
