script: |
  cd /home/ec2-user

  rm -rf devops-nginx-project
  git clone https://github.com/nikhilgeography-png/devops-nginx-project.git

  cd devops-nginx-project

  sudo fuser -k 80/tcp || true
  docker rm -f nginx-project || true

  docker build -t nginx-project .

  docker run -d -p 80:80 --name nginx-project nginx-project
